//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CTRLMusic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CTRLMusic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1_PRINCIPAL_cadastrar {
            get {
                object obj = ResourceManager.GetObject("_1_PRINCIPAL_cadastrar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1_PRINCIPAL_consultar {
            get {
                object obj = ResourceManager.GetObject("_1_PRINCIPAL_consultar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1_PRINCIPAL_deslogar {
            get {
                object obj = ResourceManager.GetObject("_1_PRINCIPAL_deslogar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1_PRINCIPAL_manual {
            get {
                object obj = ResourceManager.GetObject("_1_PRINCIPAL_manual", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _1_PRINCIPAL_vender {
            get {
                object obj = ResourceManager.GetObject("_1_PRINCIPAL_vender", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream _10_SOM_tandantantentan {
            get {
                return ResourceManager.GetStream("_10_SOM_tandantantentan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2_CADASTRAR_addguitar {
            get {
                object obj = ResourceManager.GetObject("_2_CADASTRAR_addguitar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2_CADASTRAR_addmidia {
            get {
                object obj = ResourceManager.GetObject("_2_CADASTRAR_addmidia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2_CADASTRAR_addstick {
            get {
                object obj = ResourceManager.GetObject("_2_CADASTRAR_addstick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _2_CADASTRAR_addworker {
            get {
                object obj = ResourceManager.GetObject("_2_CADASTRAR_addworker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_CONSULTAR_searchchart {
            get {
                object obj = ResourceManager.GetObject("_3_CONSULTAR_searchchart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_CONSULTAR_searchguitar {
            get {
                object obj = ResourceManager.GetObject("_3_CONSULTAR_searchguitar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_CONSULTAR_searchmidia {
            get {
                object obj = ResourceManager.GetObject("_3_CONSULTAR_searchmidia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_CONSULTAR_searchstick {
            get {
                object obj = ResourceManager.GetObject("_3_CONSULTAR_searchstick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_CONSULTAR_searchuser {
            get {
                object obj = ResourceManager.GetObject("_3_CONSULTAR_searchuser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _3_CONSULTAR_searchworker {
            get {
                object obj = ResourceManager.GetObject("_3_CONSULTAR_searchworker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4_VENDER_sellguitar {
            get {
                object obj = ResourceManager.GetObject("_4_VENDER_sellguitar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4_VENDER_sellmidia {
            get {
                object obj = ResourceManager.GetObject("_4_VENDER_sellmidia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _4_VENDER_sellstick {
            get {
                object obj = ResourceManager.GetObject("_4_VENDER_sellstick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _5_HEADER_ctrlmusicheader3 {
            get {
                object obj = ResourceManager.GetObject("_5_HEADER_ctrlmusicheader3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_chart {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_chart", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_CTRLMusic {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_CTRLMusic", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_database {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_database", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_drums {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_drums", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_lock1 {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_lock1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_midia {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_midia", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_pick {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_pick", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_product {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_product", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_user {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_user", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon _6_ICONE_worker {
            get {
                object obj = ResourceManager.GetObject("_6_ICONE_worker", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_drumstick {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_drumstick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_flute {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_flute", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_guitar {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_guitar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_midia {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_midia", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_piano {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_piano", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_pick {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_pick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_product {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_product", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_search {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap _7_PNG_worker {
            get {
                object obj = ResourceManager.GetObject("_7_PNG_worker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to externa:
        ///K:\\CTRLMusic\\CTRLMusic 2.0\\CTRLMusic\\CTRLMusic.mdf
        ///
        ///externa 2:
        ///G:\\CTRLMusic\\CTRLMusic 2.0\\CTRLMusic\\CTRLMusic.mdf
        ///
        ///interna:
        ///E:\\CTRLMusic\\CTRLMusic 2.0\\CTRLMusic\\CTRLMusic.mdf.
        /// </summary>
        public static string _9_TXT_conexao {
            get {
                return ResourceManager.GetString("_9_TXT_conexao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alaúde
        ///Armontino
        ///Baixo
        ///Bandola
        ///Balalaica
        ///Bandolim
        ///Banjo
        ///Berimbau
        ///Cavaquinho
        ///Charango
        ///Cistre
        ///Cítara
        ///Dobro
        ///Guitarra
        ///Guitarra Baiana
        ///Hardanger Fiddle
        ///Rabeca
        ///Tricordino
        ///Ukulele
        ///Viola
        ///Violino
        ///Violão
        ///Violoncelo / Cello
        ///.
        /// </summary>
        public static string _9_TXT_cordas {
            get {
                return ResourceManager.GetString("_9_TXT_cordas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lançamento
        ///Novo
        ///Antigo
        ///Usado.
        /// </summary>
        public static string _9_TXT_estados {
            get {
                return ResourceManager.GetString("_9_TXT_estados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternativo
        ///Blues / Jazz
        ///Clássica 
        ///Country
        ///Easy Listening
        ///Eletrônica
        ///Flamenco
        ///Folk / Indie
        ///Funk
        ///Gospel
        ///Instrumental
        ///Metal
        ///MPB
        ///New Age
        ///Pop Internacional
        ///Pop Nacional
        ///Rap / Hip Hop
        ///R&amp;B / Soul
        ///Reggae
        ///Rock Internacional
        ///Rock Nacional
        ///Samba
        ///Progressivo
        ///Psicodélico
        ///Trilha Sonora.
        /// </summary>
        public static string _9_TXT_generos {
            get {
                return ResourceManager.GetString("_9_TXT_generos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to norma dos parâmetros
        ///
        ///nome = pnome; 
        ///marca = pmarca;
        ///cor = pcor; 
        ///tipo = ptipo;
        ///instrumento = pins;
        ///espessura = pesp;
        ///distribuidor = pdis;
        ///tamanho = ptam;
        ///nota_fiscal = pnf;
        ///codigo = pcod;
        ///preco = ppre;
        ///quantidade = pqtd;
        ///foto = pfoto;
        ///ano_lancamento = pano;
        ///genero = pgen;
        ///artista = part;
        ///duracao = pdur;
        ///idioma = pidi;           
        ///profundidade = ppro;
        ///estado = pest;
        ///altura = palt;
        ///peso = ppeso;
        ///cod_instrumento = pcins;
        ///cod_cliente = pccli;
        ///nserie = pnser;.
        /// </summary>
        public static string _9_TXT_parâmetros {
            get {
                return ResourceManager.GetString("_9_TXT_parâmetros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agogô
        ///Atabaque
        ///Afoxé
        ///Batá
        ///Bateria
        ///Bloco sonoro
        ///Bongô
        ///Cowbell
        ///Carrilhão
        ///Casaca
        ///Castanhola
        ///Caxixi
        ///Caixa 
        ///Ceramofone
        ///Chimbau
        ///Chocalho
        ///Cuíca
        ///Conga
        ///Darbuka
        ///Ganzá
        ///Marimba
        ///Pandeiro
        ///Pratos
        ///Reco-reco
        ///Repinique
        ///Sino
        ///Sinos tubulares
        ///Surdo
        ///Tantã
        ///Triângulo
        ///Tambor
        ///Tamborim
        ///Tímpano
        ///Tom-tom
        ///Xequerê
        ///Vibrafone
        ///Xilofone
        ///Zabumba.
        /// </summary>
        public static string _9_TXT_percussão {
            get {
                return ResourceManager.GetString("_9_TXT_percussão", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bombarda
        ///Bombardão
        ///Bombardino
        ///Bugle 
        ///Charamela
        ///Contrafagote
        ///Cornetas de madeira
        ///Corneta de pistões
        ///Corne inglês
        ///Didjeridu
        ///Duduk
        ///Dulciana
        ///Dulçaina
        ///Eufônio
        ///Fagote
        ///Feliscorne
        ///Flauta
        ///Flautim/Piccolo
        ///Flauta de pan
        ///Flauta baixo
        ///Flauta doce
        ///Fulannu
        ///Gaita-de-fole
        ///Hojok
        ///Melofone
        ///Museta
        ///Oboé
        ///Oboé d&apos;amore
        ///Ocarina
        ///Oficleide
        ///Quinticlave
        ///Pífaro
        ///Pife Brasileiro
        ///Sacabuxa
        ///Sarrusofone
        ///Saxotrompa alto 
        ///Shehnai
        ///Shofar
        ///Sousafone
        ///Suona
        ///Surnay ou Surna
        ///Trompa de postilhão
        ///Trombone
        ///Trompa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string _9_TXT_sopro {
            get {
                return ResourceManager.GetString("_9_TXT_sopro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acordeão
        ///Cravo
        ///Ondas Martenot
        ///Órgão
        ///Piano
        ///Sintetizador
        ///Sampler
        ///Teclado
        ///Teremim.
        /// </summary>
        public static string _9_TXT_teclas {
            get {
                return ResourceManager.GetString("_9_TXT_teclas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CD
        ///DVD
        ///BluRay
        ///Vinil
        ///Fita cassete.
        /// </summary>
        public static string _9_TXT_tipos {
            get {
                return ResourceManager.GetString("_9_TXT_tipos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AC
        ///AL
        ///AP
        ///AM
        ///BA
        ///CE
        ///DF
        ///ES
        ///GO
        ///MA
        ///MT
        ///MS
        ///MG
        ///PA
        ///PB
        ///PR
        ///PE
        ///PI
        ///RJ
        ///RN
        ///RS
        ///RO
        ///RR
        ///SC
        ///SP
        ///SE
        ///TO.
        /// </summary>
        public static string _9_TXT_uf {
            get {
                return ResourceManager.GetString("_9_TXT_uf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] CTRLMusic_documentação {
            get {
                object obj = ResourceManager.GetObject("CTRLMusic_documentação", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
