---------------------------------------------------- ACESSORIO
CREATE TABLE ACESSORIO
(COD_ACESSORIO SERIAL,
 NOME VARCHAR(100),
 DISTRIBUIDOR VARCHAR(50),
 MARCA VARCHAR(20),
 PRECO DECIMAL(10,2),
 QUANTIDADE INTEGER,
 COR VARCHAR(15),
 MODELO VARCHAR(15),				--ATRIBUTOS
 TIPO VARCHAR(20),
 INSTRUMENTO VARCHAR(20),
 ALTURA VARCHAR(15),
 LARGURA VARCHAR(15),
 PROFUNDIDADE VARCHAR(15),
 PESO VARCHAR(15));
 
 SELECT * FROM ACESSORIO					--VISUALIZANDO TABELA

 DELETE FROM ACESSORIO
 
 ALTER TABLE ACESSORIO
 ADD CONSTRAINT PK_ACESSORIO 
 PRIMARY KEY (COD_ACESSORIO)					--INSERINDO CHAVE PRIMÁRIA
 
--------------------------------------------------------   INSTRUMENTO
CREATE TABLE INSTRUMENTO
(COD_INSTRUMENTO SERIAL,
 NOME VARCHAR(100),
 MARCA VARCHAR(30),
 DISTRIBUIDOR VARCHAR(50),
 COR VARCHAR(20),
 MODELO VARCHAR(20),					--ATRIBUTOS
 ALTURA VARCHAR(15),
 LARGURA VARCHAR(15),
 PROFUNDIDADE VARCHAR(15),
 PESO VARCHAR(15),
 TIPO VARCHAR(20),
 PRECO DECIMAL(10,2),
 QUANTIDADE INTEGER,
 INSTRUMENTO VARCHAR(50),
 ESTADO VARCHAR(15));
 
ALTER TABLE INSTRUMENTO
ADD CONSTRAINT PK_INSTRUMENTO 				--INSERINDO CHAVE PRIMÁRIA
PRIMARY KEY (COD_INSTRUMENTO)

SELECT * FROM INSTRUMENTO				--VISUALIZANDO TABELA

DELETE FROM INSTRUMENTO

                  

------------------------------------------------------------------ MIDIA
CREATE TABLE MIDIA
(COD_MIDIA SERIAL,
 NOME VARCHAR(100),
 GENERO VARCHAR(20),
 ANO_LANCAMENTO INTEGER,
 ARTISTA VARCHAR(50),
 MARCA VARCHAR(20),
 QUANTIDADE INTEGER,
 DURACAO VARCHAR(20),
 PRECO DECIMAL(10,2),
 IDIOMA VARCHAR(20),
 PROFUNDIDADE VARCHAR(20),
 ALTURA VARCHAR(20),
 PESO VARCHAR(20),
 LARGURA VARCHAR(20),
 TIPO VARCHAR(10),
 ESTADO VARCHAR(15));

 ALTER TABLE MIDIA
 ADD CONSTRAINT PK_MIDIA 
 PRIMARY KEY(COD_MIDIA)

 SELECT * FROM MIDIA

 DROP TABLE MIDIA

 ------------------------------------------------------------- FUNCIONARIO
CREATE TABLE FUNCIONARIO
(COD_FUNCIONARIO SERIAL,
 NOME VARCHAR(50),
 CPF VARCHAR(15),
 RG VARCHAR(15),
 DATA_NASCIMENTO DATE,
 DATA_CADASTRO DATE,						--ATRIBUTOS
 TURNO CHAR(1),
 RESIDENCIAL VARCHAR(15),
 CELULAR VARCHAR(15)
 EMAIL VARCHAR(50)
 GENERO VARCHAR(10));

 ALTER TABLE FUNCIONARIO
 ADD CONSTRAINT PK_FUNCIONARIO 					--INSERINDO CHAVE PRIMÁRIA
 PRIMARY KEY (COD_FUNCIONARIO)

 SELECT  * FROM FUNCIONARIO					--VISUALIZANDO TABELA

 DELETE FROM FUNCIONARIO 
 
------------------------------------------------------- USUARIO
CREATE TABLE USUARIO
(COD_USUARIO SERIAL,
 COD_FUNCIONARIO INTEGER,
 USUARIO VARCHAR(10),
 SENHA VARCHAR(10),
 CSENHA VARCHAR(10),
 ADMINISTRADOR BOOLEAN);

 ALTER TABLE USUARIO
 ADD CONSTRAINT PK_USUARIO 
 PRIMARY KEY (COD_USUARIO)
 
 ALTER TABLE USUARIO
 ADD CONSTRAINT FK_USUARIO 
 FOREIGN KEY (COD_FUNCIONARIO)
 REFERENCES FUNCIONARIO(COD_FUNCIONARIO) 

 SELECT * FROM USUARIO

 DELETE FROM USUARIO

----------------------------------------VENDA

CREATE TABLE VENDA
(COD_VENDA SERIAL, 
COD_PRODUTO INTEGER, 
NOME_PRODUTO VARCHAR(100),
QTD_PRODUTO INTEGER,
VALOR_UNI DECIMAL(10,2),
DESCONTO DECIMAL(10,2),
QTD_VENDA INTEGER,
VALOR_PAGO DECIMAL(10,2),
DATA_VENDA DATE,
VALOR_TROCO DECIMAL(10,2),
VALOR_TOTAL DECIMAL(10,2))

SELECT * FROM VENDA

ALTER TABLE VENDA
ADD CONSTRAINT PK_VENDA
PRIMARY KEY(COD_VENDA)


