CREATE TABLE [dbo].[VENDA] (
    [COD_VENDA]     INT             IDENTITY (1, 1) NOT NULL,
	[COD_FUNCIONARIO] INT NOT NULL,
    [COD_PRODUTO]   INT             NOT NULL,
    [NOME_PRODUTO]  VARCHAR (200)   NOT NULL,
    [QTD_PRODUTO]   INT             NOT NULL,
    [VALOR_UNIDADE] NUMERIC (10, 2) NOT NULL,
    [DESCONTO]      NUMERIC (10, 2) NOT NULL,
    [QTD_VENDA]     INT             NOT NULL,
    [VALOR_PAGO]    NUMERIC (10, 2) NOT NULL,
    [DATA_VENDA]    DATE            NOT NULL,
    [VALOR_TOTAL]   NUMERIC (10, 2) NOT NULL,
    [VALOR_TROCO]   NUMERIC (10, 2) NOT NULL,
    PRIMARY KEY CLUSTERED ([COD_VENDA] ASC), 
    CONSTRAINT [FK_VENDA] FOREIGN KEY (COD_FUNCIONARIO) REFERENCES FUNCIONARIO
);

